// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Infrastructure;

namespace TestApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210121152737_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TestApp.Domain.Entities.CSV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("datetime");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit")
                        .HasColumnName("is_married");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.ToTable("CSV");
                });
#pragma warning restore 612, 618
        }
    }
}
